[package]
name = "iced_tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = [
    "tokio",
    "image",
    "svg",
    "tokio",
    "canvas",
    "advanced",
] }
tokio = { version = "1.44.2", features = ["time"] }
